# Generated by Django 3.2.12 on 2022-03-09 18:04

import django.core.validators
from django.db import migrations, models
import juliany_pizza.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20220309_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='alabala', max_length=1024, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: 0899999999', regex='^(\\+\\d{1,2}\\s)?\\(?\\d{3}\\)?[\\s.-]?\\d{3}[\\s.-]?\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[juliany_pizza.utils.validators.MaxFileSizeInMbValidator(5)], verbose_name='Profile Image'),
        ),
    ]
