# Generated by Django 3.2.12 on 2022-03-15 05:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20220314_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Menu Items', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(error_messages={'name': 'That category already exists'}, max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(error_messages={'name': 'That ingredient already exists'}, max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
