# Generated by Django 3.2.12 on 2022-03-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20220315_0552'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('L', 'L'), ('XL', 'XL')], max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='size',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='sizes',
            field=models.ManyToManyField(to='menu.PizzaSize'),
        ),
    ]
