# Generated by Django 3.2.12 on 2022-03-15 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20220315_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('L', 'L'), ('XL', 'XL')], max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='sizes',
        ),
        migrations.DeleteModel(
            name='PizzaSize',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.size'),
            preserve_default=False,
        ),
    ]
