# Generated by Django 3.2.12 on 2022-03-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20220315_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(choices=[('L', 'L'), ('XL', 'XL')], error_messages={'unique': 'That size already exists.'}, max_length=2, unique=True),
        ),
    ]
