# Generated by Django 3.2.12 on 2022-03-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_auto_20220315_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='size',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='size',
            field=models.ManyToManyField(to='menu.Size'),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(choices=[('DEFAULT', 'DEFAULT'), ('L', 'L'), ('XL', 'XL'), ('FAMILY', 'FAMILY')], max_length=7),
        ),
    ]
