# Generated by Django 3.2.12 on 2022-03-15 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_auto_20220315_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='price',
        ),
    ]
