# Generated by Django 3.2.12 on 2022-03-15 08:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_remove_menuitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='name',
            field=models.CharField(default='default', max_length=255, validators=[django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
    ]
