# Generated by Django 3.2.12 on 2022-03-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_size_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(choices=[('D', 'D'), ('L', 'L'), ('XL', 'XL'), ('F', 'F')], max_length=2),
        ),
    ]
