# Generated by Django 3.2.12 on 2022-03-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.CharField(default='dsadas', max_length=1024),
            preserve_default=False,
        ),
    ]
