# Generated by Django 3.2.12 on 2022-03-28 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
