# Generated by Django 3.2.12 on 2022-04-13 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('finished', 'created')},
        ),
    ]
