name: Juliany Pizza Tests

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8
#          TODO: Not working with the heroku database, should be fixed!
#      - name: Coverage report
#        run: |
#          pip install coverage
#          coverage run --omit=*/venv/*,*/migrations/* manage.py test
#          coverage report

  heroku_git_deploy_job:
      runs-on: ubuntu-latest
      name: Git Deploy job- A job to deploy django app to heroku using git
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Deploy django to heroku
        - uses: akhileshns/heroku-deploy@v3.12.12
          with:
            heroku_app_name : ${{ secrets.HEROKU_APP_NAME }}
            heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
            heroku_email_address: 'kzborisov94@gmail.com'
            remote_branch: "main"
