name: Juliany Pizza Tests

on: [ push ]

env:
  APP_ENVIRONMENT: Development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8

      - name: Coverage report
        run: |
          pip install coverage
          coverage run --omit=*/venv/*,*/migrations/* manage.py test
          coverage report
