name: Juliany Pizza Tests

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 --output-file flake8stats.txt
      - name: Archive flake8 results
        uses: actions/upload-artifact@v3
        with:
          name: flake8-report
          retention-days: 1
      - name: Coverage report
        run: |
          pip install coverage
          coverage run manage.py test
          coverage report
          coverage xml -o coverage.xml
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          retention-days: 1
      - uses: actions/download-artifact@master
        with:
          names: flake8-report code-coverage-report
          paths: flake8stats.txt coverage.xml
      - run:
          pip install genbadge
          genbadge flake8 -i flake8stats.txt
